import { Transaction, Category } from '../types';

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: '1',
    amount: 89.90,
    type: 'expense',
    category: 'supermarket',
    description: 'Supermercado Extra',
    date: new Date('2024-09-10'),
    source: 'sms',
    accountId: '1',
    userId: 'user1',
    createdAt: new Date('2024-09-10'),
    updatedAt: new Date('2024-09-10'),
  },
  {
    id: '2',
    amount: 5000,
    type: 'income',
    category: 'salary',
    description: 'Salário Empresa XYZ',
    date: new Date('2024-09-05'),
    source: 'manual',
    accountId: '1',
    userId: 'user1',
    createdAt: new Date('2024-09-05'),
    updatedAt: new Date('2024-09-05'),
  },
  {
    id: '3',
    amount: 45.50,
    type: 'expense',
    category: 'restaurant',
    description: 'Restaurante Sabor',
    date: new Date('2024-09-09'),
    source: 'ocr',
    accountId: '1',
    userId: 'user1',
    createdAt: new Date('2024-09-09'),
    updatedAt: new Date('2024-09-09'),
  },
  {
    id: '4',
    amount: 120,
    type: 'expense',
    category: 'fuel',
    description: 'Posto Shell',
    date: new Date('2024-09-08'),
    source: 'voice',
    accountId: '2',
    userId: 'user1',
    createdAt: new Date('2024-09-08'),
    updatedAt: new Date('2024-09-08'),
  },
  {
    id: '5',
    amount: 39.90,
    type: 'expense',
    category: 'streaming',
    description: 'Netflix',
    date: new Date('2024-09-07'),
    source: 'email',
    accountId: '1',
    userId: 'user1',
    createdAt: new Date('2024-09-07'),
    updatedAt: new Date('2024-09-07'),
  },
  {
    id: '6',
    amount: 250,
    type: 'expense',
    category: 'shopping',
    description: 'Shopping Center',
    date: new Date('2024-09-06'),
    source: 'manual',
    accountId: '2',
    userId: 'user1',
    createdAt: new Date('2024-09-06'),
    updatedAt: new Date('2024-09-06'),
  },
  {
    id: '7',
    amount: 1500,
    type: 'income',
    category: 'freelance',
    description: 'Projeto Freelance',
    date: new Date('2024-09-04'),
    source: 'manual',
    accountId: '1',
    userId: 'user1',
    createdAt: new Date('2024-09-04'),
    updatedAt: new Date('2024-09-04'),
  },
  {
    id: '8',
    amount: 65,
    type: 'expense',
    category: 'uber',
    description: 'Uber Viagem',
    date: new Date('2024-09-03'),
    source: 'sms',
    accountId: '1',
    userId: 'user1',
    createdAt: new Date('2024-09-03'),
    updatedAt: new Date('2024-09-03'),
  },
];

export const MOCK_SMS_MESSAGES = [
  {
    sender: 'Nubank',
    body: 'Pagamento de R$ 89,90 realizado no cartão final 1234. Estabelecimento: Supermercado Extra.',
  },
  {
    sender: 'Banco do Brasil',
    body: 'Conta Corrente: Transferência de R$ 5.000,00 recebida via TED. Saldo disponível: R$ 8.500,00',
  },
  {
    sender: 'Inter',
    body: 'PIX enviado: R$ 45,50 para Restaurante Sabor. Confirmação: 123456',
  },
  {
    sender: 'Itaú',
    body: 'Compra aprovada: R$ 120,00. Cartão final 5678. Estabelecimento: Posto Shell.',
  },
  {
    sender: 'Mercado Pago',
    body: 'Assinatura cobrada: R$ 39,90. Netflix. Próximo vencimento: 07/10/2024.',
  },
];

export const MOCK_EMAILS = [
  {
    from: 'noreply@nubank.com.br',
    subject: 'Fatura do seu cartão de crédito',
    body: 'Sua fatura de setembro no valor de R$ 892,30 está disponível. Vencimento: 20/09/2024.',
  },
  {
    from: 'contato@mercadopago.com.br',
    subject: 'Pagamento confirmado',
    body: 'Seu pagamento de R$ 250,00 para Shopping Center foi processado com sucesso.',
  },
];

export const MOCK_CATEGORIES: Category[] = [
  { id: '1', name: 'Alimentação', icon: 'cart', color: '#FF6B6B', type: 'expense' },
  { id: '2', name: 'Transporte', icon: 'car', color: '#4ECDC4', type: 'expense' },
  { id: '3', name: 'Moradia', icon: 'home', color: '#9B59B6', type: 'expense' },
  { id: '4', name: 'Lazer', icon: 'play-circle', color: '#F1C40F', type: 'expense' },
  { id: '5', name: 'Saúde', icon: 'heart', color: '#E74C3C', type: 'expense' },
  { id: '6', name: 'Educação', icon: 'book', color: '#3498DB', type: 'expense' },
  { id: '7', name: 'Salário', icon: 'briefcase', color: '#2ECC71', type: 'income' },
  { id: '8', name: 'Freelance', icon: 'laptop', color: '#1ABC9C', type: 'income' },
  { id: '9', name: 'Investimentos', icon: 'trending-up', color: '#F39C12', type: 'income' },
];
